# ============================================================================
# HappyRepair - Docker Compose Development Environment
# ============================================================================

services:
  # PostgreSQL Database with PostGIS extension
  postgres:
    image: postgis/postgis:15-3.3
    container_name: happyrepair_postgres
    environment:
      POSTGRES_DB: happyrepair_dev
      POSTGRES_USER: happyrepair
      POSTGRES_PASSWORD: dev_password_2024
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      # Persist data
      - postgres_data:/var/lib/postgresql/data
      # Auto-run schema on first startup
      - ./backend/src/database/schema:/docker-entrypoint-initdb.d:ro
      # Backup location
      - ./backups:/backups
    networks:
      - happyrepair_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U happyrepair -d happyrepair_dev"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: happyrepair_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - happyrepair_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  happyrepair_network:
    driver: bridge